# Generated by Django 3.2.4 on 2021-06-25 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='party',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='party',
            name='message',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='party',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 25, 23, 50, 39, 40510)),
        ),
    ]
