# Generated by Django 3.2.4 on 2021-06-26 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_auto_20210625_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 27, 0, 4, 57, 493707)),
        ),
        migrations.AlterField(
            model_name='party',
            name='radius',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 0, 4, 57, 493696)),
        ),
    ]
