# Generated by Django 3.2.4 on 2021-06-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_auto_20210626_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='radius',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
