# Generated by Django 3.2.4 on 2021-06-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_alter_party_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
