# Generated by Django 3.2.4 on 2021-06-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_party_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
