# Generated by Django 3.2.4 on 2021-06-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_party_attending_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, default=256),
        ),
        migrations.AddField(
            model_name='party',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
