# Generated by Django 3.2.4 on 2021-06-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_auto_20210627_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
