# Generated by Django 3.2.4 on 2021-06-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_extendeduser_birthday'),
        ('parties', '0012_party_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='register.extendeduser'),
        ),
    ]
