# Generated by Django 3.2.4 on 2021-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0013_auto_20210627_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='ratings',
            field=models.TextField(default='{}', null=True),
        ),
    ]
