# Generated by Django 3.2.4 on 2021-06-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0014_party_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='hide_host',
            field=models.BooleanField(default=False),
        ),
    ]
