# Generated by Django 3.2.4 on 2021-06-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendreq', '0002_friendreq_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendreq',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
