# Generated by Django 3.2.4 on 2021-06-21 23:53

from django.db import migrations
import register.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=register.customfields.SeparatedValuesField(null=True),
        ),
    ]
