# Generated by Django 3.2.4 on 2021-06-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210622_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='friends',
            field=models.TextField(null=True),
        ),
    ]
