# Generated by Django 3.2.4 on 2021-06-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_extendeduser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='friends',
            field=models.TextField(default='[]', null=True),
        ),
    ]
