# Generated by Django 3.2.4 on 2021-06-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_extendeduser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={},
        ),
    ]
