# Generated by Django 3.2.4 on 2021-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_name'),
        ('register', '0008_auto_20210624_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.Group'),
        ),
    ]
