# Generated by Django 3.2.4 on 2021-06-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_auto_20210625_1727'),
        ('register', '0009_extendeduser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='attending_parties',
            field=models.ManyToManyField(blank=True, related_name='attending_parties', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='hidden_parties',
            field=models.ManyToManyField(blank=True, related_name='hidden_parties', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='invited_parties',
            field=models.ManyToManyField(blank=True, related_name='invited_parties', to='parties.Party'),
        ),
    ]
