# Generated by Django 3.2.4 on 2021-06-27 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20210626_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
