# Generated by Django 3.2.4 on 2021-06-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20210628_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
