# Generated by Django 3.2.4 on 2021-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendreq', '0003_friendreq_rejected'),
        ('register', '0015_auto_20210628_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='pending_friend_requests',
            field=models.ManyToManyField(blank=True, to='friendreq.FriendReq'),
        ),
    ]
