# Generated by Django 3.2.4 on 2021-08-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_extendeduser_pending_friend_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
