# Generated by Django 3.2.4 on 2021-08-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0015_party_hide_host'),
        ('friendreq', '0003_friendreq_rejected'),
        ('groups', '0004_alter_group_members'),
        ('register', '0021_alter_extendeduser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='attending_parties',
            field=models.ManyToManyField(blank=True, null=True, related_name='attending_parties', to='parties.Party'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='blocked',
            field=models.ManyToManyField(blank=True, null=True, related_name='_register_extendeduser_blocked_+', to='register.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_register_extendeduser_friends_+', to='register.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='hidden_parties',
            field=models.ManyToManyField(blank=True, null=True, related_name='hidden_parties', to='parties.Party'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='invited_parties',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_parties', to='parties.Party'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='my_parties',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_parties', to='parties.Party'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='pending_friend_requests',
            field=models.ManyToManyField(blank=True, null=True, to='friendreq.FriendReq'),
        ),
    ]
