# Generated by Django 3.2.4 on 2021-08-31 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0024_alter_extendeduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=register.models.upload_path),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
