# Generated by Django 3.2.4 on 2021-06-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_extendeduser_groups'),
        ('groups', '0003_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='register.ExtendedUser'),
        ),
    ]
